apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pokemon-xp
  namespace: kargo-helm
spec:
  args:
    - name: pokemon
  metrics:
    - name: pokemon-xp
      interval: 5s
      count: 5
      successCondition: result < 200
      failureLimit: 3
      provider:
        web:
          url: https://pokeapi.co/api/v2/pokemon/{{args.pokemon}}
          jsonPath: "{$.base_experience}"
