apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-helm
  namespace: kargo-helm
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
